<?php
$content = ob_start();

// Set default values for pagination variables if not set
$currentPage = $currentPage ?? 1;
$totalPages = $totalPages ?? 1;
$perPage = $perPage ?? 10;
?>
<div class="container-fluid px-4 mt-4">
    <div class="row">
        <!-- Stats Cards - Matching index.php style -->
        <div class="col-6 col-md-6 col-lg-3 mb-4">
            <div class="card shadow-sm h-100 border">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title font-weight-bold">Constituents</h5>
                    <h2 class="card-text text-primary mt-auto mb-0" id="constituentsCount">0</h2>
                </div>
            </div>
        </div>
        <div class="col-6 col-md-6 col-lg-3 mb-4">
            <div class="card shadow-sm h-100 border">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title font-weight-bold">Household</h5>
                    <h2 class="card-text text-primary mt-auto mb-0" id="householdCount">0</h2>
                </div>
            </div>
        </div>
        <div class="col-6 col-md-6 col-lg-3 mb-4">
            <div class="card shadow-sm h-100 border">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title font-weight-bold">Families</h5>
                    <h2 class="card-text text-primary mt-auto mb-0" id="familiesCount"><?= $totalFamilies ?? 0 ?></h2>
                </div>
            </div>
        </div>
        <div class="col-6 col-md-6 col-lg-3 mb-4">
            <div class="card shadow-sm h-100 border">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title font-weight-bold">Senior Citizens</h5>
                    <h2 class="card-text text-primary mt-auto mb-0" id="recentFamiliesCount"><?= $totalSeniorCitizens ?? 0 ?></h2>
                </div>
            </div>
        </div>
    </div>

    <!-- Transactions Table with Pagination - Matching index.php style -->
    <div class="mt-4">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <h4 class="font-weight-bold m-0">Transactions</h4>
            <div>
                <a href="index.php?controller=forms&action=downloadAllFormsToZip" class="btn btn-primary">
                    Download All Forms
                </a>
            </div>
        </div>
        
        <div class="table-responsive" style="max-height: 480px; overflow-y: auto;">
            <table class="table table-bordered border rounded">
                <thead class="thead-dark text-center">
                    <tr>
                        <th class="sortable" onclick="sortTable(0, this)">Doc Type</th>
                        <th class="sortable" onclick="sortTable(1, this)">Requested By</th>
                        <th class="sortable" onclick="sortTable(2, this)">Generated By</th>
                        <th class="sortable" onclick="sortTable(3, this)">Date Generated</th>
                        <th>Purpose</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (!empty($transactions) && count($transactions) > 0): ?>
                        <?php foreach ($transactions as $transaction): ?>
                            <tr>
                                <td><?= htmlspecialchars($transaction['transaction'] ?? '') ?></td>
                                <td><?= htmlspecialchars($transaction['requested_by'] ?? '') ?></td>
                                <td><?= htmlspecialchars($transaction['generated_by'] ?? '') ?></td>
                                <td><?= htmlspecialchars($transaction['date_of_transaction'] ?? '') ?></td>
                                <td><?= htmlspecialchars($transaction['purpose'] ?? '') ?></td>
                                <td>
                                    <a href="<?= $transaction['document_location'] ?? '#' ?>" target="_blank"
                                        class="btn btn-primary btn-sm">View</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="6" class="text-center">No transactions found.</td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>

        <!-- Pagination Controls - Matching index.php style -->
        <?php if (isset($totalPages) && $totalPages > 1): ?>
            <div class="row mt-3">
                <div class="col-12">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="text-muted">
                            Showing <?= count($transactions) ?> of <?= $totalRecords ?? count($transactions) ?> transactions
                        </div>
                        <nav aria-label="Transactions pagination">
                            <ul class="pagination pagination-sm mb-0">
                                <!-- First Page Button -->
                                <li class="page-item <?= $currentPage <= 1 ? 'disabled' : '' ?>">
                                    <a class="page-link" href="index.php?controller=dashboard&action=index&page=1" aria-label="First">
                                        <span aria-hidden="true">&laquo;&laquo;</span>
                                    </a>
                                </li>

                                <!-- Previous Button -->
                                <li class="page-item <?= $currentPage <= 1 ? 'disabled' : '' ?>">
                                    <a class="page-link" href="index.php?controller=dashboard&action=index&page=<?= max(1, $currentPage - 1) ?>" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>

                                <?php
                                $startPage = max(1, $currentPage - 2);
                                $endPage = min($totalPages, $currentPage + 2);

                                if ($endPage - $startPage + 1 < 5) {
                                    if ($startPage == 1) {
                                        $endPage = min($totalPages, $startPage + 4);
                                    } elseif ($endPage == $totalPages) {
                                        $startPage = max(1, $endPage - 4);
                                    }
                                }

                                for ($i = $startPage; $i <= $endPage; $i++):
                                ?>
                                    <li class="page-item <?= $i == $currentPage ? 'active' : '' ?>">
                                        <a class="page-link" href="index.php?controller=dashboard&action=index&page=<?= $i ?>"><?= $i ?></a>
                                    </li>
                                <?php endfor; ?>

                                <!-- Next Button -->
                                <li class="page-item <?= $currentPage >= $totalPages ? 'disabled' : '' ?>">
                                    <a class="page-link" href="index.php?controller=dashboard&action=index&page=<?= min($totalPages, $currentPage + 1) ?>" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>

                                <!-- Last Page Button -->
                                <li class="page-item <?= $currentPage >= $totalPages ? 'disabled' : '' ?>">
                                    <a class="page-link" href="index.php?controller=dashboard&action=index&page=<?= $totalPages ?>" aria-label="Last">
                                        <span aria-hidden="true">&raquo;&raquo;</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>

<script>
    function animateCounter(id, target) {
        let count = 0;
        const interval = setInterval(() => {
            count += Math.ceil(target / 100);
            if (count >= target) {
                count = target;
                clearInterval(interval);
            }
            document.getElementById(id).textContent = count;
        }, 20);
    }

    // Sorting function to match index.php
    function sortTable(columnIndex, header) {
        const table = document.querySelector('.table-responsive table');
        const rows = Array.from(table.tBodies[0].rows);
        const isAscending = header ? header.getAttribute('data-sort-order') === 'asc' : false;
        const newOrder = isAscending ? 'desc' : 'asc';

        rows.sort((a, b) => {
            let cellA = a.cells[columnIndex].textContent.trim();
            let cellB = b.cells[columnIndex].textContent.trim();
            
            // For date columns (index 3)
            if (columnIndex === 3) {
                cellA = new Date(cellA).getTime() || 0;
                cellB = new Date(cellB).getTime() || 0;
            } else {
                cellA = cellA.toLowerCase();
                cellB = cellB.toLowerCase();
            }

            if (cellA < cellB) return isAscending ? -1 : 1;
            if (cellA > cellB) return isAscending ? 1 : -1;
            return 0;
        });

        rows.forEach(row => table.tBodies[0].appendChild(row));
        
        if (header) {
            // Reset all headers and update the clicked one
            document.querySelectorAll('th.sortable').forEach(th => th.removeAttribute('data-sort-order'));
            header.setAttribute('data-sort-order', newOrder);
        }
    }

    // Initialize counter animations
    const totalConstituents = <?= $totalConstituents ?? 0 ?>;
    const totalHouseholds = <?= $totalHouseholds ?? 0 ?>;

    animateCounter('constituentsCount', totalConstituents);
    animateCounter('householdCount', totalHouseholds);
    animateCounter('familiesCount', <?= $totalFamilies ?? 0 ?>);
    animateCounter('recentFamiliesCount', <?= $totalSeniorCitizens ?? 0 ?>);
    
    // Sort transactions by date (column index 3) in descending order by default
    document.addEventListener('DOMContentLoaded', function() {
        const dateHeader = document.querySelector('.table-responsive table th:nth-child(4)');
        if (dateHeader) {
            // Set sort order to desc directly on the header
            dateHeader.setAttribute('data-sort-order', 'desc');
            // Call sort with the date column (index 3)
            sortTable(3, dateHeader);
        }
    });
</script>

<style>
    th.sortable {
        cursor: pointer;
    }

    th.sortable:after {
        content: '\25B4';
        font-size: 0.8em;
        margin-left: 5px;
        visibility: hidden;
    }

    th.sortable[data-sort-order="asc"]:after {
        visibility: visible;
        content: '\25B4';
    }

    th.sortable[data-sort-order="desc"]:after {
        visibility: visible;
        content: '\25BE';
    }
</style>

<?php
$content = ob_get_clean();
require_once('app/Views/layouts/main.php');
?>